[project]
name = "py-blockchain"
version = "0.1.0"
description = "A simple blockchain implementation in Python"
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.3",
    "tabulate>=0.9.0",
    "colorama>=0.4.6",
]

[tool.poetry.dependencies]
python = "^3.8"
tabulate = "^0.9.0" 

